Feature/save related wiki items
CAKES-coding/swe574-group2 pull request #101
Opened 2021-11-30 10:40 UTC by emrecalik

2021-11-30 10:41 UTC, emrecalik commented
![tag](https://user-images.githubusercontent.com/62518089/144032375-e1eb5d4b-5f5b-4c99-b2e4-27d867193477.png)
![tag-inheritance](https://user-images.githubusercontent.com/62518089/144032388-1724ca82-c33c-4530-abd1-8f98b198ae3b.png)

2021-12-04 11:14 UTC, kenankural commented on Project/Wikode/templates/wikodeApp/articleDetail.html
> -                        {{ item.ForeName }} {{ item.LastName }}
Bu iş bu PR'ın kapsamının dışında aslında, burada yazarın isim linki varsa onu önyüzde göstermeyi yazıyoruz. Bir sonrakine bunu farklı bir PR ile gösterebiliriz abi.

2021-12-04 11:26 UTC, active-sludge commented on Project/Wikode/wikodeApp/utils/articleManager.py
> +                        if identifier is not None:
Double negative if clause olmus.

`if identifier is not None:` 
yerine
`if identifier` yapilabilir.

2021-12-04 11:26 UTC, kenankural approved these changes

2021-12-04 11:26 UTC, kenankural commented on Project/Wikode/templates/wikodeApp/articleDetail.html
> +                        {% if item.Identifier %}
Bu iş bu PR'ın kapsamının dışında aslında, burada yazarın isim linki varsa onu önyüzde göstermeyi yazıyoruz. Bir sonrakine bunu farklı bir PR ile gösterebiliriz abi.

2021-12-04 11:27 UTC, kenankural commented
@emrecalik Eline sağlık abi.

2021-12-04 11:28 UTC, semihsolmaz requested changes

2021-12-04 11:28 UTC, semihsolmaz commented on Project/Wikode/wikodeApp/views.py
> +import wikodeApp.models
Bu satıra gerek yok bir alt satırda explicitly import ediyoruz zaten modelleri o sekilde ilerleyelim.

2021-12-05 14:34 UTC, merged