Refactor tag the whole article feature. #67
CAKES-coding/swe574-group2 pull request #102
Opened 2021-12-03 20:09 UTC by emrecalik

**Describe the solution you'd like**
The user shall be redirected to an article detail page.
The user shall tag the whole article.

2021-12-03 20:37 UTC, jajimentol commented
@emrecalik bu tag yazdığımız yerin yüksekliğini çözemedik mi

2021-12-04 11:45 UTC, active-sludge commented
@jajimentol tag yuksekligi PR'ini onayladim az once.

2021-12-04 11:51 UTC, semihsolmaz requested changes

2021-12-04 11:51 UTC, semihsolmaz commented on Project/Wikode/wikodeApp/tests.py
> +from mock import Mock
Dışlarıdan bir library kullanmaya başladığımız da, ilgili library'y, requirements.txt dosyasına ekleyelim.

2021-12-04 17:10 UTC, active-sludge commented on Project/Wikode/wikodeApp/tests.py
> +from mock import Mock
Ayrica bu Mock library'si ubuntu makinede çalışıyor olmalı. 
Yani Mac'te çalışan library'nin, linux'ta da çalıştığından emin olunmalı.

2021-12-05 14:26 UTC, semihsolmaz approved these changes

2021-12-05 14:26 UTC, merged