Navigation item Profile button now navigates to /myprofile instead of…
CAKES-coding/swe574-group2 pull request #122
Opened 2021-12-10 22:03 UTC by active-sludge

… /profile.

/profile will be used for another user's profile.
Added dummy user link on homepage.
Added user or profile if statement to reuse profile.html.
Add myprofile url.

2021-12-12 11:09 UTC, jajimentol commented
Followers/Followees shall be displayed with names, not emails. @active-sludge

2021-12-13 13:02 UTC, active-sludge commented
On the homepage, user links are hardcoded for demonstration purposes.
There need to be at least 3 users, in order for the links to work.

2021-12-13 17:09 UTC, semihsolmaz requested changes
just a typo in view name and corresponding URL

2021-12-13 17:09 UTC, semihsolmaz commented on Project/Wikode/wikodeApp/urls.py
> +    path('profile/<int:pk>', views.getProfilePageOfOtherfUser, name='getProfilePageOfOtherfUser'),
getProfilePageOfOtherfUser typo in view.

2021-12-13 17:09 UTC, semihsolmaz commented on Project/Wikode/wikodeApp/views.py
> +def getProfilePageOfOtherfUser(request, pk):
getProfilePageOfOtherfUser typo

2021-12-13 17:44 UTC, semihsolmaz approved these changes

2021-12-13 17:44 UTC, merged