Add clear tag fragment button. #107
CAKES-coding/swe574-group2 pull request #160
Opened 2021-12-22 15:34 UTC by emrecalik

2021-12-25 09:04 UTC, kenankural requested changes
Indexler sıfırlanıyor ama abstractdaki html tagleri temizlenmediği için taglenen alan sarı ile boyanmıyor ve indexler değişiyor.

2021-12-26 12:46 UTC, emrecalik commented
Seçilen texti iptal ettiğimizde abstract text html'inin temizlenmesi özelliği eklendi.

2021-12-26 20:22 UTC, active-sludge approved these changes

2021-12-27 15:13 UTC, merged

2021-12-27 15:13 UTC, kenankural commented
@emrecalik eline sağlık