Feature/suggestion record model
CAKES-coding/swe574-group2 pull request #170
Opened 2021-12-29 14:15 UTC by jajimentol

Suggestion manager is created.

two ultimate methods for:
- article suggestions
- user suggestions

are usable. Please test your case in the branch.

2021-12-29 14:15 UTC, jajimentol commented
Related to #126 and #124

2021-12-29 19:51 UTC, emrecalik requested changes
`get_random_user` fonksiyonu loop'tan çıkamıyor.

2021-12-29 19:51 UTC, emrecalik commented on Project/Wikode/wikodeApp/utils/suggestionManager.py
> +                self.user_list.append(user)
loop'tan çıkamıyor.

2021-12-30 09:17 UTC, jajimentol commented on Project/Wikode/wikodeApp/utils/suggestionManager.py
> +                self.user_list.append(user)
az sayıda kullanıcı olursa oluyor sanırım

2021-12-30 09:19 UTC, jajimentol commented on Project/Wikode/wikodeApp/utils/suggestionManager.py
> +                self.user_list.append(user)
5'ten fazla kullanıcı varsa random_usera girecek şekilde ayarladım, daha az kullanıcı varsa 3'ten az user suggest edebilir

2021-12-30 17:32 UTC, active-sludge approved these changes

2021-12-30 17:40 UTC, active-sludge commented
@jajimentol Birbirini followlayan kullanici sayisi 3'ten az oldugundaki bug icin fix yapildiginda merge edelim.

2021-12-30 17:53 UTC, emrecalik commented
Semih'in son yaptığı tagleme modülüyle çakışma yok. Lokalde test edildi. Çalışıyor.

2022-01-01 13:13 UTC, emrecalik commented
Homepage sayfasını art arda 3 defa yenilediğimde `get_user_suggestion()` metodu aşağıdaki gibi döndü:

1. `[[<User: admin@tagpub.com>], None, <User: emre.calik01@gmail.com>]`

2. `[[<User: admin@tagpub.com>], None, <User: can@gmail.com>]`

3. `[[<User: admin@tagpub.com>], None, <User: semih@gmail.com>]`

2022-01-02 12:08 UTC, active-sludge approved these changes

2022-01-02 12:10 UTC, emrecalik approved these changes
eline sağlık. @jajimentol

2022-01-02 12:11 UTC, merged